### PR TITLE
[#17] Improved .gitignore file

### LINKED ISSUE #17: Improve .gitignore
Suited for android studio and OSX.

Removes dependencies on built / generated files.

### PR DESCRIPTION
**Pull request by dansuh17**
Fixes #17 
- removed dependencies on built / generated files
- suited for android studio and macOS

### CODE REVIEW

**Comment by heewoonam** [comment]
LGTM

**Comment by harry2636** [comment]
I think we already added those lines in the link below, because we decided to separate the gitignore files in each directory.(Android/toonDra and server)
https://github.com/deNsuh/toonDra/blob/master/Android/toonDra/.gitignore

**Comment by dansuh17** [comment]
For some reason the Android Studio keeps creating those files and it's becoming annoying.
It would not damage the project if we keep a master gitignore.

**Comment by harry2636** [comment]
LGTM

**Pull request merged**
